vault:
  driver: local
  localRoot: ./.overmind/vault
logging:
  level: debug
http:
  address: 127.0.0.1:8080
cli:
  mode: remote
  endpoint: http://localhost:8080
index:
  driver: sqlite
  path: ./.overmind/index.db
