// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookmarks.sql

package sqlitedb

import (
	"context"
)

const upsertBookmark = `-- name: UpsertBookmark :exec
INSERT INTO bookmarks (note_id, url) VALUES (?, ?)
ON CONFLICT(note_id) DO UPDATE SET url=excluded.url
`

type UpsertBookmarkParams struct {
	NoteID string `db:"note_id"`
	Url    string `db:"url"`
}

func (q *Queries) UpsertBookmark(ctx context.Context, arg UpsertBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, upsertBookmark, arg.NoteID, arg.Url)
	return err
}
