// Package sqlitedb contains SQL bindings generated by sqlc for the derived note index.
// Change the SQL query sources and regenerate the bindings rather than editing generated files.
package sqlitedb
