// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habits.sql

package sqlitedb

import (
	"context"
)

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const deleteNoteTags = `-- name: DeleteNoteTags :exec
DELETE FROM note_tags WHERE note_id = ?
`

func (q *Queries) DeleteNoteTags(ctx context.Context, noteID string) error {
	_, err := q.db.ExecContext(ctx, deleteNoteTags, noteID)
	return err
}

const ensureTag = `-- name: EnsureTag :exec
INSERT INTO tags (name) VALUES (?) ON CONFLICT(name) DO NOTHING
`

func (q *Queries) EnsureTag(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, ensureTag, name)
	return err
}

const habitByID = `-- name: HabitByID :one
SELECT n.id, n.type, n.path, h.title, n.created_at, n.updated_at,
 h.target_amount, h.unit, h.period
FROM notes n JOIN habits h ON h.note_id = n.id WHERE n.id = ? AND n.type = 'habit'
`

type HabitByIDRow struct {
	ID           string  `db:"id"`
	Type         string  `db:"type"`
	Path         string  `db:"path"`
	Title        string  `db:"title"`
	CreatedAt    string  `db:"created_at"`
	UpdatedAt    string  `db:"updated_at"`
	TargetAmount float64 `db:"target_amount"`
	Unit         string  `db:"unit"`
	Period       string  `db:"period"`
}

func (q *Queries) HabitByID(ctx context.Context, id string) (HabitByIDRow, error) {
	row := q.db.QueryRowContext(ctx, habitByID, id)
	var i HabitByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Path,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetAmount,
		&i.Unit,
		&i.Period,
	)
	return i, err
}

const insertNoteTag = `-- name: InsertNoteTag :exec
INSERT INTO note_tags (note_id, tag, position) VALUES (?, ?, ?)
`

type InsertNoteTagParams struct {
	NoteID   string `db:"note_id"`
	Tag      string `db:"tag"`
	Position int64  `db:"position"`
}

func (q *Queries) InsertNoteTag(ctx context.Context, arg InsertNoteTagParams) error {
	_, err := q.db.ExecContext(ctx, insertNoteTag, arg.NoteID, arg.Tag, arg.Position)
	return err
}

const tagsByNoteID = `-- name: TagsByNoteID :many
SELECT tag FROM note_tags WHERE note_id = ? ORDER BY position
`

func (q *Queries) TagsByNoteID(ctx context.Context, noteID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, tagsByNoteID, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHabit = `-- name: UpsertHabit :exec
INSERT INTO habits (note_id, title, target_amount, unit, period) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(note_id) DO UPDATE SET title=excluded.title, target_amount=excluded.target_amount, unit=excluded.unit, period=excluded.period
`

type UpsertHabitParams struct {
	NoteID       string  `db:"note_id"`
	Title        string  `db:"title"`
	TargetAmount float64 `db:"target_amount"`
	Unit         string  `db:"unit"`
	Period       string  `db:"period"`
}

func (q *Queries) UpsertHabit(ctx context.Context, arg UpsertHabitParams) error {
	_, err := q.db.ExecContext(ctx, upsertHabit,
		arg.NoteID,
		arg.Title,
		arg.TargetAmount,
		arg.Unit,
		arg.Period,
	)
	return err
}

const upsertNote = `-- name: UpsertNote :exec
INSERT INTO notes (id, type, path, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET type=excluded.type, path=excluded.path,
 created_at=excluded.created_at, updated_at=excluded.updated_at
`

type UpsertNoteParams struct {
	ID        string `db:"id"`
	Type      string `db:"type"`
	Path      string `db:"path"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

func (q *Queries) UpsertNote(ctx context.Context, arg UpsertNoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertNote,
		arg.ID,
		arg.Type,
		arg.Path,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
