// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox.sql

package sqlitedb

import (
	"context"
)

const upsertInbox = `-- name: UpsertInbox :exec
INSERT INTO inbox (note_id, content) VALUES (?, ?)
ON CONFLICT(note_id) DO UPDATE SET content=excluded.content
`

type UpsertInboxParams struct {
	NoteID  string `db:"note_id"`
	Content string `db:"content"`
}

func (q *Queries) UpsertInbox(ctx context.Context, arg UpsertInboxParams) error {
	_, err := q.db.ExecContext(ctx, upsertInbox, arg.NoteID, arg.Content)
	return err
}
