// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journals.sql

package sqlitedb

import (
	"context"
)

const journalExists = `-- name: JournalExists :one
SELECT EXISTS(SELECT 1 FROM journals WHERE date=?)
`

func (q *Queries) JournalExists(ctx context.Context, date string) (bool, error) {
	row := q.db.QueryRowContext(ctx, journalExists, date)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertJournal = `-- name: UpsertJournal :exec
INSERT INTO journals(note_id,date) VALUES(?,?)
ON CONFLICT(note_id) DO UPDATE SET date=excluded.date
`

type UpsertJournalParams struct {
	NoteID string `db:"note_id"`
	Date   string `db:"date"`
}

func (q *Queries) UpsertJournal(ctx context.Context, arg UpsertJournalParams) error {
	_, err := q.db.ExecContext(ctx, upsertJournal, arg.NoteID, arg.Date)
	return err
}
