// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

type Bookmark struct {
	NoteID string `db:"note_id"`
	Url    string `db:"url"`
}

type Group struct {
	Name string `db:"name"`
}

type Habit struct {
	NoteID       string  `db:"note_id"`
	Title        string  `db:"title"`
	TargetAmount float64 `db:"target_amount"`
	Unit         string  `db:"unit"`
	Period       string  `db:"period"`
}

type Inbox struct {
	NoteID  string `db:"note_id"`
	Content string `db:"content"`
}

type Journal struct {
	NoteID string `db:"note_id"`
	Date   string `db:"date"`
}

type Note struct {
	ID        string `db:"id"`
	Type      string `db:"type"`
	Path      string `db:"path"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

type NoteTag struct {
	NoteID   string `db:"note_id"`
	Tag      string `db:"tag"`
	Position int64  `db:"position"`
}

type Page struct {
	NoteID string `db:"note_id"`
	Title  string `db:"title"`
	Area   string `db:"area"`
}

type Person struct {
	NoteID string `db:"note_id"`
	Name   string `db:"name"`
}

type PersonGroup struct {
	PersonID  string `db:"person_id"`
	GroupName string `db:"group_name"`
	Position  int64  `db:"position"`
}

type Tag struct {
	Name string `db:"name"`
}
