// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlitedb

import (
	"context"
)

const clearAllNoteTags = `-- name: ClearAllNoteTags :exec
DELETE FROM note_tags
`

func (q *Queries) ClearAllNoteTags(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllNoteTags)
	return err
}

const clearAllPersonGroups = `-- name: ClearAllPersonGroups :exec
DELETE FROM person_groups
`

func (q *Queries) ClearAllPersonGroups(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllPersonGroups)
	return err
}

const clearBookmarks = `-- name: ClearBookmarks :exec
DELETE FROM bookmarks
`

func (q *Queries) ClearBookmarks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearBookmarks)
	return err
}

const clearGroups = `-- name: ClearGroups :exec
DELETE FROM groups
`

func (q *Queries) ClearGroups(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearGroups)
	return err
}

const clearHabits = `-- name: ClearHabits :exec
DELETE FROM habits
`

func (q *Queries) ClearHabits(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearHabits)
	return err
}

const clearInbox = `-- name: ClearInbox :exec
DELETE FROM inbox
`

func (q *Queries) ClearInbox(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearInbox)
	return err
}

const clearJournals = `-- name: ClearJournals :exec
DELETE FROM journals
`

func (q *Queries) ClearJournals(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearJournals)
	return err
}

const clearNotes = `-- name: ClearNotes :exec
DELETE FROM notes
`

func (q *Queries) ClearNotes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearNotes)
	return err
}

const clearPages = `-- name: ClearPages :exec
DELETE FROM pages
`

func (q *Queries) ClearPages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearPages)
	return err
}

const clearPersons = `-- name: ClearPersons :exec
DELETE FROM persons
`

func (q *Queries) ClearPersons(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearPersons)
	return err
}

const clearTags = `-- name: ClearTags :exec
DELETE FROM tags
`

func (q *Queries) ClearTags(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTags)
	return err
}

const findNotes = `-- name: FindNotes :many
SELECT n.id, n.type, n.updated_at,
 CAST(CASE n.type
 WHEN 'habit' THEN h.title
 WHEN 'person' THEN p.name
 WHEN 'bookmark' THEN b.url
 WHEN 'inbox' THEN substr(i.content, 1, 120)
 WHEN 'page' THEN pg.title
 WHEN 'journal' THEN j.date
 ELSE '' END AS TEXT) AS label,
 CAST((SELECT json_group_array(tag) FROM
 (SELECT tag FROM note_tags WHERE note_id = n.id ORDER BY position)) AS TEXT) AS tags
FROM notes n
LEFT JOIN habits h ON h.note_id = n.id
LEFT JOIN persons p ON p.note_id = n.id
LEFT JOIN bookmarks b ON b.note_id = n.id
LEFT JOIN inbox i ON i.note_id = n.id
LEFT JOIN pages pg ON pg.note_id = n.id
LEFT JOIN journals j ON j.note_id = n.id
WHERE (?1 = '' OR n.type = ?1)
 AND (?2 = '' OR EXISTS
 (SELECT 1 FROM note_tags nt WHERE nt.note_id = n.id AND nt.tag = ?2))
ORDER BY n.updated_at DESC, n.id ASC
LIMIT ?4 OFFSET ?3
`

type FindNotesParams struct {
	NoteType   interface{} `db:"note_type"`
	Tag        interface{} `db:"tag"`
	PageOffset int64       `db:"page_offset"`
	PageLimit  int64       `db:"page_limit"`
}

type FindNotesRow struct {
	ID        string `db:"id"`
	Type      string `db:"type"`
	UpdatedAt string `db:"updated_at"`
	Label     string `db:"label"`
	Tags      string `db:"tags"`
}

func (q *Queries) FindNotes(ctx context.Context, arg FindNotesParams) ([]FindNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, findNotes,
		arg.NoteType,
		arg.Tag,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNotesRow
	for rows.Next() {
		var i FindNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.UpdatedAt,
			&i.Label,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
