// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package sqlitedb

import (
	"context"
)

const upsertPage = `-- name: UpsertPage :exec
INSERT INTO pages(note_id,title,area) VALUES(?,?,?)
ON CONFLICT(note_id) DO UPDATE SET title=excluded.title,area=excluded.area
`

type UpsertPageParams struct {
	NoteID string `db:"note_id"`
	Title  string `db:"title"`
	Area   string `db:"area"`
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertPage, arg.NoteID, arg.Title, arg.Area)
	return err
}
