// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: persons.sql

package sqlitedb

import (
	"context"
)

const deletePersonGroups = `-- name: DeletePersonGroups :exec
DELETE FROM person_groups WHERE person_id = ?
`

func (q *Queries) DeletePersonGroups(ctx context.Context, personID string) error {
	_, err := q.db.ExecContext(ctx, deletePersonGroups, personID)
	return err
}

const ensureGroup = `-- name: EnsureGroup :exec
INSERT INTO groups (name) VALUES (?) ON CONFLICT(name) DO NOTHING
`

func (q *Queries) EnsureGroup(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, ensureGroup, name)
	return err
}

const findGroups = `-- name: FindGroups :many
SELECT DISTINCT group_name FROM person_groups ORDER BY group_name
`

func (q *Queries) FindGroups(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, findGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_name string
		if err := rows.Scan(&group_name); err != nil {
			return nil, err
		}
		items = append(items, group_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupsByPersonID = `-- name: GroupsByPersonID :many
SELECT group_name FROM person_groups WHERE person_id = ? ORDER BY position
`

func (q *Queries) GroupsByPersonID(ctx context.Context, personID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, groupsByPersonID, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var group_name string
		if err := rows.Scan(&group_name); err != nil {
			return nil, err
		}
		items = append(items, group_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPersonGroup = `-- name: InsertPersonGroup :exec
INSERT INTO person_groups (person_id, group_name, position) VALUES (?, ?, ?)
`

type InsertPersonGroupParams struct {
	PersonID  string `db:"person_id"`
	GroupName string `db:"group_name"`
	Position  int64  `db:"position"`
}

func (q *Queries) InsertPersonGroup(ctx context.Context, arg InsertPersonGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertPersonGroup, arg.PersonID, arg.GroupName, arg.Position)
	return err
}

const personByID = `-- name: PersonByID :one
SELECT n.id, n.type, n.path, n.created_at, n.updated_at, p.name
FROM notes n JOIN persons p ON p.note_id = n.id WHERE n.id = ? AND n.type = 'person'
`

type PersonByIDRow struct {
	ID        string `db:"id"`
	Type      string `db:"type"`
	Path      string `db:"path"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
	Name      string `db:"name"`
}

func (q *Queries) PersonByID(ctx context.Context, id string) (PersonByIDRow, error) {
	row := q.db.QueryRowContext(ctx, personByID, id)
	var i PersonByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const upsertPerson = `-- name: UpsertPerson :exec
INSERT INTO persons (note_id, name) VALUES (?, ?)
ON CONFLICT(note_id) DO UPDATE SET name=excluded.name
`

type UpsertPersonParams struct {
	NoteID string `db:"note_id"`
	Name   string `db:"name"`
}

func (q *Queries) UpsertPerson(ctx context.Context, arg UpsertPersonParams) error {
	_, err := q.db.ExecContext(ctx, upsertPerson, arg.NoteID, arg.Name)
	return err
}
