// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

type Note struct {
	ID        string `db:"id"`
	Kind      string `db:"kind"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

type NoteAttribute struct {
	NoteID string `db:"note_id"`
	Name   string `db:"name"`
	Value  string `db:"value"`
}

type NoteTag struct {
	NoteID   string `db:"note_id"`
	Tag      string `db:"tag"`
	Position int64  `db:"position"`
}
