// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

type Document struct {
	ID        string `db:"id"`
	Kind      string `db:"kind"`
	Title     string `db:"title"`
	Area      string `db:"area"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

type DocumentAttribute struct {
	DocumentID string `db:"document_id"`
	Name       string `db:"name"`
	Value      string `db:"value"`
}

type DocumentTag struct {
	DocumentID string `db:"document_id"`
	Tag        string `db:"tag"`
	Position   int64  `db:"position"`
}
