// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlitedb

import (
	"context"
)

const deleteNoteAttributes = `-- name: DeleteNoteAttributes :exec
DELETE FROM note_attributes
WHERE note_id = ?
`

func (q *Queries) DeleteNoteAttributes(ctx context.Context, noteID string) error {
	_, err := q.db.ExecContext(ctx, deleteNoteAttributes, noteID)
	return err
}

const deleteNoteTags = `-- name: DeleteNoteTags :exec
DELETE FROM note_tags
WHERE note_id = ?
`

func (q *Queries) DeleteNoteTags(ctx context.Context, noteID string) error {
	_, err := q.db.ExecContext(ctx, deleteNoteTags, noteID)
	return err
}

const insertNoteAttribute = `-- name: InsertNoteAttribute :exec
INSERT INTO note_attributes (note_id, name, value)
VALUES (?, ?, ?)
`

type InsertNoteAttributeParams struct {
	NoteID string `db:"note_id"`
	Name   string `db:"name"`
	Value  string `db:"value"`
}

func (q *Queries) InsertNoteAttribute(ctx context.Context, arg InsertNoteAttributeParams) error {
	_, err := q.db.ExecContext(ctx, insertNoteAttribute, arg.NoteID, arg.Name, arg.Value)
	return err
}

const insertNoteTag = `-- name: InsertNoteTag :exec
INSERT INTO note_tags (note_id, tag, position)
VALUES (?, ?, ?)
`

type InsertNoteTagParams struct {
	NoteID   string `db:"note_id"`
	Tag      string `db:"tag"`
	Position int64  `db:"position"`
}

func (q *Queries) InsertNoteTag(ctx context.Context, arg InsertNoteTagParams) error {
	_, err := q.db.ExecContext(ctx, insertNoteTag, arg.NoteID, arg.Tag, arg.Position)
	return err
}

const journalExists = `-- name: JournalExists :one
SELECT EXISTS (
    SELECT 1
    FROM notes
    JOIN note_attributes ON note_attributes.note_id = notes.id
    WHERE notes.kind = 'journal'
      AND note_attributes.name = 'date'
      AND note_attributes.value = ?
)
`

func (q *Queries) JournalExists(ctx context.Context, value string) (bool, error) {
	row := q.db.QueryRowContext(ctx, journalExists, value)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const journalID = `-- name: JournalID :one
SELECT notes.id
FROM notes
JOIN note_attributes ON note_attributes.note_id = notes.id
WHERE notes.kind = 'journal'
  AND note_attributes.name = 'date'
  AND note_attributes.value = ?
LIMIT 1
`

func (q *Queries) JournalID(ctx context.Context, value string) (string, error) {
	row := q.db.QueryRowContext(ctx, journalID, value)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listNoteAttributes = `-- name: ListNoteAttributes :many
SELECT note_id, name, value
FROM note_attributes
ORDER BY note_id, name
`

func (q *Queries) ListNoteAttributes(ctx context.Context) ([]NoteAttribute, error) {
	rows, err := q.db.QueryContext(ctx, listNoteAttributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteAttribute
	for rows.Next() {
		var i NoteAttribute
		if err := rows.Scan(&i.NoteID, &i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteTags = `-- name: ListNoteTags :many
SELECT note_id, tag, position
FROM note_tags
ORDER BY note_id, position
`

func (q *Queries) ListNoteTags(ctx context.Context) ([]NoteTag, error) {
	rows, err := q.db.QueryContext(ctx, listNoteTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteTag
	for rows.Next() {
		var i NoteTag
		if err := rows.Scan(&i.NoteID, &i.Tag, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotes = `-- name: ListNotes :many
SELECT id, kind, created_at, updated_at
FROM notes
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNote = `-- name: UpsertNote :exec
INSERT INTO notes (id, kind, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    kind = excluded.kind,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at
`

type UpsertNoteParams struct {
	ID        string `db:"id"`
	Kind      string `db:"kind"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

func (q *Queries) UpsertNote(ctx context.Context, arg UpsertNoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertNote,
		arg.ID,
		arg.Kind,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
