// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlitedb

import (
	"context"
)

const deleteNoteAttributes = `-- name: DeleteNoteAttributes :exec
DELETE FROM note_attributes
WHERE note_id = ?
`

func (q *Queries) DeleteNoteAttributes(ctx context.Context, noteID string) error {
	_, err := q.db.ExecContext(ctx, deleteNoteAttributes, noteID)
	return err
}

const deleteNoteTags = `-- name: DeleteNoteTags :exec
DELETE FROM note_tags
WHERE note_id = ?
`

func (q *Queries) DeleteNoteTags(ctx context.Context, noteID string) error {
	_, err := q.db.ExecContext(ctx, deleteNoteTags, noteID)
	return err
}

const insertNoteAttribute = `-- name: InsertNoteAttribute :exec
INSERT INTO note_attributes (note_id, name, value)
VALUES (?, ?, ?)
`

type InsertNoteAttributeParams struct {
	NoteID string `db:"note_id"`
	Name   string `db:"name"`
	Value  string `db:"value"`
}

func (q *Queries) InsertNoteAttribute(ctx context.Context, arg InsertNoteAttributeParams) error {
	_, err := q.db.ExecContext(ctx, insertNoteAttribute, arg.NoteID, arg.Name, arg.Value)
	return err
}

const insertNoteTag = `-- name: InsertNoteTag :exec
INSERT INTO note_tags (note_id, tag, position)
VALUES (?, ?, ?)
`

type InsertNoteTagParams struct {
	NoteID   string `db:"note_id"`
	Tag      string `db:"tag"`
	Position int64  `db:"position"`
}

func (q *Queries) InsertNoteTag(ctx context.Context, arg InsertNoteTagParams) error {
	_, err := q.db.ExecContext(ctx, insertNoteTag, arg.NoteID, arg.Tag, arg.Position)
	return err
}

const upsertNote = `-- name: UpsertNote :exec
INSERT INTO notes (id, kind, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    kind = excluded.kind,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at
`

type UpsertNoteParams struct {
	ID        string `db:"id"`
	Kind      string `db:"kind"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

func (q *Queries) UpsertNote(ctx context.Context, arg UpsertNoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertNote,
		arg.ID,
		arg.Kind,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
