// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlitedb

import (
	"context"
)

const deleteAllDocuments = `-- name: DeleteAllDocuments :exec
DELETE FROM documents
`

func (q *Queries) DeleteAllDocuments(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDocuments)
	return err
}

const deleteDocumentAttributes = `-- name: DeleteDocumentAttributes :exec
DELETE FROM document_attributes
WHERE document_id = ?
`

func (q *Queries) DeleteDocumentAttributes(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentAttributes, documentID)
	return err
}

const deleteDocumentTags = `-- name: DeleteDocumentTags :exec
DELETE FROM document_tags
WHERE document_id = ?
`

func (q *Queries) DeleteDocumentTags(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentTags, documentID)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, path, kind, title, created_at, updated_at
FROM documents
WHERE id = ?
`

func (q *Queries) GetDocumentByID(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Kind,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDocumentAttribute = `-- name: InsertDocumentAttribute :exec
INSERT INTO document_attributes (document_id, name, value)
VALUES (?, ?, ?)
`

type InsertDocumentAttributeParams struct {
	DocumentID string `db:"document_id"`
	Name       string `db:"name"`
	Value      string `db:"value"`
}

func (q *Queries) InsertDocumentAttribute(ctx context.Context, arg InsertDocumentAttributeParams) error {
	_, err := q.db.ExecContext(ctx, insertDocumentAttribute, arg.DocumentID, arg.Name, arg.Value)
	return err
}

const insertDocumentTag = `-- name: InsertDocumentTag :exec
INSERT INTO document_tags (document_id, tag, position)
VALUES (?, ?, ?)
`

type InsertDocumentTagParams struct {
	DocumentID string `db:"document_id"`
	Tag        string `db:"tag"`
	Position   int64  `db:"position"`
}

func (q *Queries) InsertDocumentTag(ctx context.Context, arg InsertDocumentTagParams) error {
	_, err := q.db.ExecContext(ctx, insertDocumentTag, arg.DocumentID, arg.Tag, arg.Position)
	return err
}

const listDocumentAttributes = `-- name: ListDocumentAttributes :many
SELECT name, value
FROM document_attributes
WHERE document_id = ?
ORDER BY name
`

type ListDocumentAttributesRow struct {
	Name  string `db:"name"`
	Value string `db:"value"`
}

func (q *Queries) ListDocumentAttributes(ctx context.Context, documentID string) ([]ListDocumentAttributesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentAttributes, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentAttributesRow
	for rows.Next() {
		var i ListDocumentAttributesRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentTags = `-- name: ListDocumentTags :many
SELECT tag
FROM document_tags
WHERE document_id = ?
ORDER BY position
`

func (q *Queries) ListDocumentTags(ctx context.Context, documentID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentTags, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, path, kind
FROM documents AS document
WHERE (CAST(?1 AS TEXT) = '' OR document.kind = CAST(?1 AS TEXT))
  AND (CAST(?2 AS TEXT) = ''
       OR instr(document.path, CAST(?2 AS TEXT)) = 1)
  AND NOT EXISTS (
      SELECT 1
      FROM json_each(CAST(?3 AS TEXT)) AS requested_tag
      WHERE NOT EXISTS (
          SELECT 1
          FROM document_tags AS document_tag
          WHERE document_tag.document_id = document.id
            AND document_tag.tag = requested_tag.value
      )
  )
ORDER BY document.path, document.id
`

type ListDocumentsParams struct {
	Kind       string `db:"kind"`
	PathPrefix string `db:"path_prefix"`
	TagsJson   string `db:"tags_json"`
}

type ListDocumentsRow struct {
	ID   string `db:"id"`
	Path string `db:"path"`
	Kind string `db:"kind"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, arg.Kind, arg.PathPrefix, arg.TagsJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(&i.ID, &i.Path, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocument = `-- name: UpsertDocument :exec
INSERT INTO documents (id, path, kind, title, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    path = excluded.path,
    kind = excluded.kind,
    title = excluded.title,
    created_at = excluded.created_at,
    updated_at = excluded.updated_at
`

type UpsertDocumentParams struct {
	ID        string `db:"id"`
	Path      string `db:"path"`
	Kind      string `db:"kind"`
	Title     string `db:"title"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.ExecContext(ctx, upsertDocument,
		arg.ID,
		arg.Path,
		arg.Kind,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
