// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

type Document struct {
	ID      string `db:"id"`
	Path    string `db:"path"`
	Content []byte `db:"content"`
}

type DocumentAttribute struct {
	DocumentID string `db:"document_id"`
	Name       string `db:"name"`
	Value      string `db:"value"`
}
